### ISSUE TITLE
Wrong theme icon displayed in production

### ISSUE THREAD

**Issue by Anees-Asghar** [leic-pt/resumos-leic#938]
In a development environment things run as we expect them to, but in production environment when you visit the website in dark mode the DarkModeOff icon is displayed.

**Comment by diogotcorreia** [comment]
Nice catch!
No idea why this happens tho :thinking: 

Using React Dev tools, the hook values seem normal.
In fact, they are exactly the same as in development...
![image](https://user-images.githubusercontent.com/7467891/216469051-b652cd68-a339-4293-be92-45c85868d72f.png)

I've noticed that the Virtual DOM seems okay, because when you toggle the theme for the first time, the actual component changes (while the DOM does not, since it had the incorrect icon).
For some reason I haven't figured out, the Virtual DOM is not matching with the actual DOM :cry:

**Comment by Anees-Asghar** [comment]
Exactly! 

Some surface level debugging also left me perplexed. The value of 'darkMode' (the variable based on which we show one icon or the other) is correct at all times both in production and development, i.e., there is no reason for this to happen.

I'll look into it in more detail as soon as I find some time.
